#index:
#    path: /
#    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky/number/{id}
  controller: App\Controller\LuckyController::number
  defaults:
    id: 66
